server:
  port: 8080

  tomcat:
    mbean-registry:
      enabled: true
      
spring:
  profiles:
    default: local

  application:
    name: bamboo-forest_backend

  config:
    import:
      - security/application-db.yml
      - security/application-oauth2.yml
      - security/application-jwt.yml
      - security/application-paymentgateway.yml

  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

management:
  server:
    port: 1010
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: info, health, prometheus
    jmx:
      exposure:
        exclude: '*'
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
    prometheus:
      enabled: true
