global:
  scrape_interval: 1m
  scrape_timeout: 15s
  evaluation_interval: 2m

  external_labels:
    monitor: 'monitor'
  query_log_file: query_log_file.log

scrape_configs:
  - job_name: 'monitoring-item'
    metrics_path: '/actuator/prometheus'
    honor_labels: false
    honor_timestamps: false
    scheme: 'http'

    ec2_sd_configs:
      - region: ap-northeast-2
        port: 1010
        access_key: AmazonEC2ReadOnlyAccess Access Key
        secret_key: AmazonEC2ReadOnlyAccess Secret Key
        filters:
          - name: tag:PrometheusScrape
            values:
              - Enabled

    relabel_configs:
      - source_labels: [ __meta_ec2_tag_Name ]
        target_label: instance
      - source_labels: [ __meta_ec2_private_ip ]
        regex: '(.*)'
        replacement: '${1}:1010'
        action: replace
        target_label: __address__
      - source_labels: [ __meta_ec2_tag_group ]
        target_label: group
      - source_labels: [ __meta_ec2_instance_type ]
        target_label: instance_type
      - target_label: application
        replacement: "Bamboo Forest"
      - target_label: namespace
        replacement: "API Server"
